name: CI
on: [push, pull_request]
jobs:
  build:
    name: Test rebuild
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, v16.16.0, '*']

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run rebuild